letter = "Hey my name is {} and I am from {}"
country = "India"
name = "Rohit"

print(letter.format(name, country))

#DOCSTRINGS
#PYTHON DOCSTRINGS ARE THE STRING LITERALS THAT APPEAR RIGHT AFTER THE DEFINITION OF A FUNCTION, METHOD, CLASS, OR MODULE. 
# THEY ARE USED TO DOCUMENT THE PURPOSE AND USAGE OF THE CODE.
# A DOCSTRING IS ENCLOSED IN TRIPLE QUOTES (""" """) AND CAN SPAN MULTIPLE LINES.
# THE DOCSTRING CAN BE ACCESSED USING THE __doc__ ATTRIBUTE OF THE FUNCTION, CLASS, OR MODULE.
# DOCSTRINGS ARE IMPORTANT FOR CODE MAINTENANCE AND HELP OTHER DEVELOPERS UNDERSTAND THE FUNCTIONALITY OF THE CODE WITHOUT HAVING TO READ THROUGH THE ENTIRE IMPLEMENTATION.
#DOCSTRING ARE THE CODE EXPLANATION OF THE FUNCTION, CLASS OR MODULE. THEY ARE USED TO DOCUMENT THE PURPOSE AND USAGE OF THE CODE. 
# LIKE COMMENTS, DOCSTRINGS ARE ALSO USED TO EXPLAIN THE CODE, BUT THEY ARE MORE FORMAL AND STRUCTURED THAN COMMENTS.
# THEY ARE NOT INGORED BY THE INTERPRETER AND CAN BE ACCESSED AT RUNTIME, MAKING THEM USEFUL FOR DOCUMENTATION AND HELP SYSTEMS.
def add(a, b):
    """This function adds two numbers and returns the result."""
    return a + b
print(add(5, 3))
print(add.__doc__) #to print the docstring of the function add

